ELSER produces token-weight pairs as output from the input text and the query.
The {es} {ref}/sparse-vector.html[`sparse_vector`] field type can store these
token-weight pairs as numeric feature vectors. The index must have a field with
the `sparse_vector` field type to index the tokens that ELSER generates.

To create a mapping for your ELSER index, refer to the <<elser-mappings,Create the index mapping section>>
of the tutorial. The example
shows how to create an index mapping for `my-index` that defines the
`my_embeddings.tokens` field - which will contain the ELSER output - as a
`sparse_vector` field.

[source,bash]
----
curl -X PUT "${ES_URL}/my-index" \
-H "Authorization: ApiKey ${API_KEY}" \
-H "Content-Type: application/json" \
-d'
{
  "mappings": {
    "properties": {
      "my_tokens": {   <1>
        "type": "sparse_vector"   <2>
      },
      "my_text_field": {   <3>
        "type": "text"   <4>
      }
    }
  }
}
'
----

<1> The name of the field that will contain the tokens generated by ELSER.

<2> The field that contains the tokens must be a `sparse_vector` field.

<3> The name of the field from which to create the sparse vector representation.
In this example, the name of the field is `my_text_field`.

<4> The field type is `text` in this example.
