name: "Community documentation request"
description: Request a documentation change as a community contributor.
title: "[Community]: "
labels: ["community"]
body:
  - type: markdown
    attributes:
      value: |
        This issue template is for non-Elastic employees who want to request a change to Elastic documentation. **If you are an Elastic employee, please use the internal issue template instead.**
        
        This form is for documentation requests only, not for product bugs, support requests, or feature requests.

        This form will create an issue that Elastic's docs team will triage and prioritize. You can also open a PR instead. Thanks for taking the time to fill out this request!
  - type: textarea
    id: link
    attributes:
      label: What documentation page or section is affected
      description: Include the URL for the page where you are seeing the problem. Screenshots are also helpful.
    validations:
      required: true
  - type: textarea
    id: related
    attributes:
      label: What should change?
      description: What is wrong with the docs, what did you expect to see, and why should the docs change?
    validations:
      required: true
  - type: textarea
    id: moreinfo
    attributes:
      label: Additional info
      description: Anything else we should know?
    validations:
      required: false