name: "Internal documentation request (Elastic employees)"
description: Request a documentation improvement, addition, or change for Elastic docs.
title: "[Internal]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this request. Use this form for documentation work only. If you need to report a product bug or request product behavior changes, please use the appropriate product workflow instead.

        This form will create an issue that the documentation team will triage and prioritize. Filling it out as early and as clearly as possible helps us scope the work and plan it well.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe what needs to be documented. What details do users need to know about?
      placeholder: |
        What: We're introducing new feature A.
        When: This feature will launch at the completion of project B.
        Why: This feature will make X, Y, and Z easier for the user.
    validations:
      required: true
  - type: textarea
    id: related
    attributes:
      label: Resources
      description: Where can the documentation team learn more about this feature?
      placeholder: |
        This feature was implemented in {link_to_PR}.

        This feature was scoped and researched in {link_to_issue}.

        Context for the feature is described in {link_to_internal_doc}.
    validations:
      required: true
  - type: dropdown
    id: doc-set
    attributes:
      label: Which deployment methods does this change impact?
      description: Knowing this information helps us to update the right content and tag it appropriately.
      options:
        - Elastic On-Prem and Cloud (all)
        - Elastic On-Prem only (ECE, ECK, or self-managed)
        - Elastic Cloud (Hosted and Serverless) only
        - Elastic Cloud Hosted only
        - Elastic Cloud Serverless only
        - Unknown
      default: 5
    validations:
      required: true
  - type: textarea
    id: doc-set-differences
    attributes:
      label: Feature differences
      description: If you selected multiple deployment methods above, describe how the feature differs in each one. Otherwise, leave this blank.
      placeholder: The feature is identical in all deployment methods.
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: What Elastic Stack release is this request related to?
      description: Some requests may be tied to the Elastic Stack release schedule. Some, like Serverless requests, may not. Please select an option.
      options:
        - 'N/A'
        - '8.19'
        - '9.0'
        - '9.1'
        - '9.2'
        - '9.3'
        - '9.4'
        - '9.5'
        - '9.6'
        - '9.7'
        - '9.8'
      default: 0
    validations:
      required: true
  - type: input
    id: release-serverless
    attributes:
      label: Serverless release
      description: If relevant, when do you expect the feature to be promoted and available in the _**serverless production environment**_?
      placeholder: The week of April 1, 2024
    validations:
      required: false
  - type: dropdown
    id: collaboration
    attributes:
      label: Collaboration model
      description: If new content is needed, who do you expect to create the initial draft?
      options:
        - "The documentation team will create the first draft"
        - "The product or engineering team will create the first draft"
        - "We expect to collaborate on the first draft"
        - "Unknown"
        - "Other (please describe below)"
      default: 3
    validations:
      required: true
  - type: textarea
    id: contact
    attributes:
      label: Point of contact.
      description: Please assign at least one point of contact using the GitHub `@` mention. Add as many stakeholders as you'd like.
      value: "**Main contact:** @\n\n**Stakeholders:**\n"
    validations:
      required: true
