[[elasticsearch-api-conventions]]
= {es} API conventions

// :description: The {es-serverless} REST APIs have conventions for headers and request bodies.
// :keywords: serverless, elasticsearch, API, reference

You can run {es} API requests in **{dev-tools-app} → Console**.
For example:

[source,shell]
----
GET _cat/indices?v=true
----

Check out <<devtools-run-api-requests-in-the-console>>.

[discrete]
[[elasticsearch-api-conventions-request-headers]]
== Request headers

When you call {es} APIs outside of the Console, you must provide a request header.
The {es} APIs support the `Authorization`, `Content-Type`, and `X-Opaque-Id` headers.

[discrete]
[[elasticsearch-api-conventions-authorization]]
=== Authorization

{es} APIs use key-based authentication.
You must create an API key and use the encoded value in the request header.
For example:

[source,bash]
----
curl -X GET "${ES_URL}/_cat/indices?v=true" \
  -H "Authorization: ApiKey ${API_KEY}"
----

To get API keys for the {es} endpoint (`${ES_URL}`) for a project, refer to <<elasticsearch-get-started>>.

[discrete]
[[elasticsearch-api-conventions-content-type]]
=== Content-type

The type of the content sent in a request body must be specified using the `Content-Type` header.
For example:

[source,bash]
----
curl -X GET "${ES_URL}/_search?pretty" \
  -H "Authorization: ApiKey ${API_KEY}" \
  -H "Content-Type: application/json" \
  -d '
  {
    "query": {
      "match_all": { "boost" : 1.2 }
    }
  }
'
----

The value of this header must map to one of the formats that the API supports.
Most APIs support JSON, YAML, CBOR, and SMILE.
The bulk and multi-search APIs support NDJSON, JSON, and SMILE; other types will result in an error response.

If you use the `source` query string parameter, you must specify the content type with the `source_content_type` query string parameter.

{es} APIs support only UTF-8-encoded JSON.
Any other encoding headings sent with a request are ignored.
Responses are also UTF-8 encoded.

////
/*
TBD: Is this something you specify in the request header or find in the response header?
### Traceparent

{es} APIs support a `traceparent` HTTP header using the [official W3C trace context spec](https://www.w3.org/TR/trace-context/#traceparent-header).
You can use the `traceparent` header to trace requests across Elastic products and other services.
Because it's used only for traces, you can safely generate a unique `traceparent` header for each request.

{es} APIs surface the header's `trace-id` value as `trace.id` in the:

* JSON {es} server logs
* Slow logs
* Deprecation logs

For example, a `traceparent` value of `00-0af7651916cd43dd8448eb211c80319c-b7ad6b7169203331-01` would produce the following
`trace.id` value in the logs: `0af7651916cd43dd8448eb211c80319c`.
*/
////

[discrete]
[[elasticsearch-api-conventions-x-opaque-id]]
=== X-Opaque-Id

You can pass an `X-Opaque-Id` HTTP header to track the origin of a request in {es} logs and tasks.
For example:

[source,bash]
----
curl -X GET "${ES_URL}/_search?pretty" \
  -H "Authorization: ApiKey ${API_KEY}" \
  -H "Content-Type: application/json" \
  -H "X-Opaque-Id: 123456" \
  -d '
  {
    "query": {
      "match_all": { "boost" : 1.2 }
    }
  }
'
----

{es} surfaces the `X-Opaque-Id` value in the:

* Response of any request that includes the header
* Task management API response
* Slow logs
* Deprecation logs

////
/* MISSING LINKS
* Response of any request that includes the header
* \<\<_identifying_running_tasks,Task management API>> response
* \<\<_identifying_search_slow_log_origin,Slow logs>>
* <DocBadge><DocIcon size="s" type="unlink" title="missing link"/> missing link</DocBadge>{/*  <DocLink id="enElasticsearchReferenceLogging" section="deprecation-logging">Deprecation logs</DocLink>
*/
////

For the deprecation logs, {es} also uses the `X-Opaque-Id` value to throttle and deduplicate deprecation warnings.

////
/* MISSING LINKS
See \<\<_deprecation_logs_throttling>>.
*/
////

The `X-Opaque-Id` header accepts any arbitrary value.
However, it is recommended that you limit these values to a finite set, such as an ID per client.
Don't generate a unique `X-Opaque-Id` header for every request.
Too many unique `X-Opaque-Id` values can prevent {es} from deduplicating warnings in the deprecation logs.

[discrete]
[[elasticsearch-api-conventions-request-bodies]]
== Request bodies

A number of {es} APIs with GET operations--most notably the search API--support a request body.
While the GET operation makes sense in the context of retrieving information, GET requests with a body are not supported by all HTTP libraries.

All {es} APIs with GET operations that require a body can also be submitted as POST requests.
Alternatively, you can pass the request body as the `source` query string parameter when using GET.
When you use this method, the `source_content_type` parameter should also be passed with a media type value that indicates the format of the source, such as `application/json`.

////
/*
TBD: The examples in this section don't current seem to work.
Error: no handler found for uri [.../_search?pretty=true] and method [GET]"

## Date math

Most {es} APIs that accept an index or index alias argument support date math.
Date math name resolution enables you to search a range of time series indices or index aliases rather than searching all of your indices and filtering the results.
Limiting the number of searched indices reduces cluster load and improves search performance.
For example, if you are searching for errors in your daily logs, you can use a date math name template to restrict the search to the past two days.

A date math name takes the following form:

```txt
<static_name{date_math_expr{date_format|time_zone}}>
```
- `static_name` is static text.
- `date_math_expr` is a dynamic date math expression that computes the date dynamically.
- `date_format` is the optional format in which the computed date should be rendered. Defaults to `yyyy.MM.dd`. The format should be compatible with [java-time](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html).
- `time_zone` is the optional time zone. Defaults to `UTC`.

<DocCallOut title="Pay attention to the use of lower and uppercase letters in the date_format.">
For example, `mm` denotes the minute of the hour, while `MM` denotes the month of the year.
Similarly `hh` denotes the hour in the `1-12` range in combination with `AM/PM`, while `HH` denotes the hour in the `0-23` 24-hour range.
</DocCallOut>

Date math expressions are resolved independent of the locale.
Consequently, you cannot use any calendars other than the Gregorian calendar.

You must enclose date math names in angle brackets.
If you use the name in a request path, special characters must be URI encoded.
For example, `<my-index-{now/d}>` is encoded as `%3Cmy-index-%7Bnow%2Fd%7D%3E`.

The special characters used for date rounding must be URI encoded.
For example:

|  |  |
|---|---|
| `<` | `%3C` |
| `>` | `%3E` |
| `/` | `%2F` |
| `{` | `%7B` |
| `}` | `%7D` |
| `\|` | `%7C` |
| `+` | `%2B` |
| `:` | `%3A` |
| `,` | `%2C` |

The following example shows different forms of date math names and the final names they resolve to given the current time is 22nd March 2024 noon UTC:

| Expression | Resolves to |
|---|---|
| `<logstash-{now/d}>`                      | `logstash-2024.03.22` |
| `<logstash-{now/M}>`                      | `logstash-2024.03.01` |
| `<logstash-{now/M{yyyy.MM}}>`             | `logstash-2024.03` |
| `<logstash-{now/M-1M{yyyy.MM}}>`          | `logstash-2024.02` |
| `<logstash-{now/d{yyyy.MM.dd\|+12:00}}>`  | `logstash-2024.03.23` |

To use the characters `{` and `}` in the static part of a name template, escape them with a backslash `\`.
For example, `<elastic\\\{ON\\\}-{now/M}>` resolves to `elastic{ON}-2024.03.01`

The following example shows a search request that searches the {ls} indices for the past three days, assuming the indices use the default {ls} index name format (`logstash-YYYY.MM.dd`):

```console
# <logstash-{now/d-2d}>,<logstash-{now/d-1d}>,<logstash-{now/d}>
curl -X GET "${ES_URL}/%3Clogstash-%7Bnow%2Fd-2d%7D%3E%2C%3Clogstash-%7Bnow%2Fd-1d%7D%3E%2C%3Clogstash-%7Bnow%2Fd%7D%3E/_search" \
-H "Authorization: ApiKey ${API_KEY}" \
-H "Content-Type: application/json" \
-d '
{
  "query" : {
    "match": {
      "test": "data"
    }
  }
}
'
```
*/
////
