[[elasticsearch-explore-your-data-visualize-your-data]]
= Visualize your data

// :description: Build dynamic dashboards and visualizations for your {es} data.
// :keywords: serverless, elasticsearch, visualize, how to

preview:[]

The best way to understand your data is to visualize it.

Elastic provides a wide range of pre-built dashboards for visualizing data from a variety of sources.
These dashboards are loaded automatically when you install https://www.elastic.co/docs/current/integrations[Elastic integrations].

You can also create new dashboards and visualizations based on your data views to get a full picture of your data.

In your {es} project, go to **Dashboards** to see existing dashboards or create your own.

Notice you can filter the list of dashboards:

* Use the text search field to filter by name or description.
* Use the **Tags** menu to filter by tag. To create a new tag or edit existing tags, click **Manage tags**.
* Click a dashboard's tags to toggle filtering for each tag.

[discrete]
[[elasticsearch-explore-your-data-visualize-your-data-create-new-dashboards]]
== Create new dashboards

To create a new dashboard, click **Create dashboard** and begin adding visualizations.
You can create charts, graphs, maps, tables, and other types of visualizations from your data, or you can add visualizations from the library.

You can also add other types of panels — such as filters, links, and text — and add controls like time sliders.

For more information about creating dashboards, refer to the {kibana-ref}/dashboard.html[{kib} documentation].

[NOTE]
====
The {kib} documentation is written for {kib} users, but the steps for serverless are very similar.
====
