[[elasticsearch-ingest-your-data]]
= Ingest your data

// :description: Add data to your {es-serverless} project.
// :keywords: serverless, elasticsearch, ingest, overview

You have many options for ingesting, or indexing, data into {es}:

* <<elasticsearch-ingest-data-through-api,{es} API>>
* <<elasticsearch-ingest-data-through-integrations-connector-client,Connector clients>>
* <<elasticsearch-ingest-data-file-upload,File Uploader>>
* <<elasticsearch-ingest-data-through-beats,{beats}>>
* <<elasticsearch-ingest-data-through-logstash,{ls}>>
* https://github.com/elastic/crawler[Elastic Open Web Crawler]

The best ingest option(s) for your use case depends on whether you are indexing general content or time series (timestamped) data.

**General content**

General content includes HTML pages, catalogs, files, and other content that does not update continuously.
This data can be updated, but the value of the content remains relatively constant over time.
Use connector clients to sync data from a range of popular data sources to {es}.
You can also send data directly to {es} from your application using the API.

[discrete]
[[elasticsearch-ingest-time-series-data]]
**Times series (timestamped) data**

Time series, or timestamped data, describes data that changes frequently and "flows" over time, such as stock quotes, system metrics, and network traffic data.
Use {beats} or {ls} to collect time series data.
