[[elasticsearch-ingest-your-data]]
= Ingest your data

// :description: Add data to your {es-serverless} project.
// :keywords: serverless, elasticsearch, ingest, overview

The best ingest option(s) for your use case depends on whether you are indexing general content or time series (timestamped) data.

[discrete]
[[es-ingestion-overview-apis]]
== Ingest data using APIs

You can use the <<elasticsearch-http-apis,{es} REST APIs>> to add data to your {es} indices, using any HTTP client, including the <<elasticsearch-clients,{es} client libraries>>.

While the {es} APIs can be used for any data type, Elastic provides specialized tools that optimize ingestion for specific use cases.

[discrete]
[[es-ingestion-overview-general-content]]
== Ingest general content

General content is typically text-heavy data that does not have a timestamp.
This could be data like knowledge bases, website content, product catalogs, and more.

You can use these specialized tools to add general content to {es} indices:

* <<elasticsearch-ingest-data-through-integrations-connector-client,Connector clients>>
* https://github.com/elastic/crawler[Elastic Open Web Crawler]
* <<elasticsearch-ingest-data-file-upload,File Uploader>>

[discrete]
[[elasticsearch-ingest-time-series-data]]
== Ingest time series data

Time series, or timestamped data, describes data that changes frequently and "flows" over time, such as stock quotes, system metrics, and network traffic data.

You can use these specialized tools to add timestamped data to {es} data streams:

* <<elasticsearch-ingest-data-through-beats,{beats}>>
* <<elasticsearch-ingest-data-through-logstash,{ls}>>
