[[general-serverless-billing]]
= Serverless billing dimensions

// :description: Understand how usage affects serverless pricing.
// :keywords: serverless, general, billing, pricing model

Elastic Cloud serverless billing is based on your usage across these dimensions:

* <<offerings,Offerings>>
* <<add-ons,Add-ons>>

[discrete]
[[offerings]]
== Offerings

To learn about billing dimensions for specific offerings, refer to:

* <<elasticsearch-billing>>
* <<observability-billing>>
* <<security-billing>>

[discrete]
[[add-ons]]
== Add-ons

[discrete]
[[general-serverless-billing-data-out]]
=== Data out

_Data out_ accounts for all of the traffic coming out of a serverless project.
This includes search results, as well as monitoring data sent from the project.
The same rate applies regardless of the destination of the data, whether to the internet,
another region, or a cloud provider account in the same region.
Data coming out of the project through AWS PrivateLink, GCP Private Service Connect,
or Azure Private Link is also considered data out.

[discrete]
[[general-serverless-billing-support]]
=== Support

If your subscription level is Standard, there is no separate charge for Support reflected on your bill.
If your subscription level is Gold, Platinum, or Enterprise, a charge is made for Support as a percentage (%) of the ECUs.
To find out more about our support levels, go to https://www.elastic.co/support[https://www.elastic.co/support].
