[[elasticsearch-manage-project]]
= Manage your projects

// :description: Configure project-wide features and usage.
// :keywords: serverless, elasticsearch, project, manage

To manage a project:

. Navigate to https://cloud.elastic.co/[cloud.elastic.co].
. Log in to your Elastic Cloud account.
. Select your project from the **Serverless projects** panel and click **Manage**.

From the project page, you can:

* **Rename your project**. In the **Overview** section, click **Edit** next to the project's name.
* **Manage data and integrations**. Update your project data, including storage settings, indices, and data views, directly in your project.
* **Manage API keys**. Access your project and interact with its data programmatically using {es} APIs.
* **Manage members**. Add members and manage their access to this project or other resources of your organization.

[discrete]
[[elasticsearch-manage-project-search-ai-lake-settings]]
== Search AI Lake settings

Once ingested, your data is stored in cost-efficient, general storage. A cache layer is available on top of the general storage for recent and frequently queried data that provides faster search speed. Data in this cache layer is considered **search-ready**.

Together, these data storage layers form your project's **Search AI Lake**.

The total volume of search-ready data is the sum of the following:

. The volume of non-time series project data
. The volume of time series project data included in the Search Boost Window

Each project type offers different settings that let you adjust the performance and volume of search-ready data, as well as the features available in your projects.

[discrete]
[[elasticsearch-manage-project-search-power-settings]]
|===
| Setting | Description | Available in

| **Search Power**
a| Search Power controls the speed of searches against your data. With Search Power, you can improve search performance by adding more resources for querying, or you can reduce provisioned resources to cut costs.
Choose from three Search Power settings:

**On-demand:** Autoscales based on data and search load, with a lower minimum baseline for resource use. This flexibility results in more variable query latency and reduced maximum throughput.

**Performant:** Delivers consistently low latency and autoscales to accommodate moderately high query throughput.

**High-throughput:** Optimized for high-throughput scenarios, autoscaling to maintain query latency even at very high query volumes.
| {es-badge}

| **Search Boost Window**
a| Non-time series data is always considered search-ready. The **Search Boost Window** determines the volume of time series project data that will be considered search-ready.

Increasing the window results in a bigger portion of time series project data included in the total search-ready data volume.
| {es-badge}

| **Data Retention**
a| Data retention policies determine how long your project data is retained.

You can specify different retention periods for specific data streams in your project.
| {es-badge}{obs-badge}{sec-badge}

|
a| **Maximum data retention period**

When enabled, this setting determines the maximum length of time that data can be retained in any data streams of this project.

Editing this setting replaces the data retention set for all data streams of the project that have a longer data retention defined. Data older than the new maximum retention period that you set is permanently deleted.
| {sec-badge}

|
a| **Default data retention period**

When enabled, this setting determines the default retention period that is automatically applied to all data streams in your project that do not have a custom retention period already set.
| {sec-badge}

| **Project features**
| Controls <<project-features-add-ons,feature tiers and add-on options>> for your {elastic-sec} project.
| {sec-badge}
|===

[discrete]
[[project-features-add-ons]]
== Project features and add-ons

{sec-badge} For {elastic-sec} projects, edit the **Project features** to select a feature tier and enable add-on options for specific use cases.

|===
| Feature tier | Description and add-ons

| **Security Analytics Essentials**
a| Standard security analytics, detections, investigations, and collaborations. Allows these add-ons:

* **Endpoint Protection Essentials**: endpoint protections with {elastic-defend}.
* **Cloud Protection Essentials**: Cloud native security features.

| **Security Analytics Complete**
a| Everything in **Security Analytics Essentials** plus advanced features such as entity analytics, threat intelligence, and more. Allows these add-ons:

* **Endpoint Protection Complete**: Everything in **Endpoint Protection Essentials** plus advanced endpoint detection and response features.
* **Cloud Protection Complete**: Everything in **Cloud Protection Essentials** plus advanced cloud security features.
|===

[discrete]
[[elasticsearch-manage-project-downgrading-the-feature-tier]]
=== Downgrading the feature tier

When you downgrade your Security project features selection from **Security Analytics Complete** to **Security Analytics Essentials**, the following features become unavailable:

* All Entity Analytics features
* The ability to use certain entity analytics-related integration packages, such as:
+
** Data Exfiltration detection
** Lateral Movement detection
** Living off the Land Attack detection
* Intelligence Indicators page
* External rule action connectors
* Case connectors
* Endpoint response actions history
* Endpoint host isolation exceptions
* AI Assistant
* Attack discovery

And, the following data may be permanently deleted:

* AI Assistant conversation history
* AI Assistant settings
* Entity Analytics user and host risk scores
* Entity Analytics asset criticality information
* Detection rule external connector settings
* Detection rule response action settings
