[[general-manage-project-with-api]]
= Using the Project Management REST API

// :description: Manage your organization's serverless projects using the REST API.
// :keywords: serverless, project, manage, rest, api

You can manage serverless projects using the https://www.elastic.co/docs/api/doc/elastic-cloud-serverless[Elastic Cloud Serverless REST API]. This API allows you to create, update, and delete projects, as well as manage project features and usage.

[TIP]
====
More APIs let you interact with data, capabilities, and settings inside of specific projects. Refer to the https://www.elastic.co/docs/api[Serverless API reference page].
====

[discrete]
[[general-manage-project-with-api-api-principles]]
== API Principles

* The Elastic Cloud REST API is built following REST principles:
+
** Resources (such as projects) are represented as URIs.
** Standard HTTP response codes and verbs are used (GET, POST, PUT, PATCH and DELETE).
** API calls are stateless. Every request that you make happens in isolation from other calls and must include all the information necessary to fulfill the request.
* JSON is the data interchange format.

[discrete]
[[general-manage-project-with-api-authentication]]
== Authentication

API keys are used to authenticate requests to the Elastic Cloud REST API.
Learn how to https://www.elastic.co/guide/en/cloud/current/ec-api-authentication.html[create API keys].

You must provide the API key for all API requests in the `Authorization` header as follows:

[source,bash]
----
"Authorization: ApiKey $API_KEY"
----

For example, if you interact with the API using the `curl` command:

[source,bash]
----
curl -H "Authorization: ApiKey essu_..." https://api.elastic-cloud.com/api/v1/serverless/projects/elasticsearch
----

[discrete]
[[general-manage-project-with-api-open-api-specification]]
== Open API Specification

The Project Management API is documented using the https://en.wikipedia.org/wiki/OpenAPI_Specification[OpenAPI Specification]. The current supported version of the specification is `3.0`.

For details, check the https://www.elastic.co/docs/api/doc/elastic-cloud-serverless[API reference] or download the https://www.elastic.co/docs/api/doc/elastic-cloud-serverless.yaml[OpenAPI Specification].

This specification can be used to generate client SDKs, or on tools that support it, such as the https://editor.swagger.io[Swagger Editor].

[discrete]
[[general-manage-project-with-api-examples]]
== Examples

To try the examples in this section:

. https://www.elastic.co/guide/en/cloud/current/ec-api-authentication.html[Create an API key].
. Store the generated API key as an environment variable so that you don't need to specify it again for each request:
+
[source,bash]
----
export API_KEY="YOUR_GENERATED_API_KEY"
----

[discrete]
[[general-manage-project-with-api-create-a-serverless-elasticsearch-project]]
=== Create an {es-serverless} project

[source,bash]
----
curl -H "Authorization: ApiKey $API_KEY" \
     -H "Content-Type: application/json" \
     "https://api.elastic-cloud.com/api/v1/serverless/projects/elasticsearch" \
     -XPOST --data '{
        "name": "My project",  <1>
        "region_id": "aws-us-east-1"  <2>
     }'
----

<1> Replace **`My project`** with a more descriptive name in this call.

<2> You can <<general-manage-project-with-api-list-available-regions,obtain a list of available regions>>.

The response from the create project request will include the created project details, such as the project ID,
the credentials to access the project, and the endpoints to access different apps such as {es} and Kibana.

Example of `Create project` response:

[source,json]
----
{
    "id": "cace8e65457043698ed3d99da2f053f6",
    "endpoints": {
        "elasticsearch": "https://sample-project-c990cb.es.us-east-1.aws.elastic.cloud",
        "kibana": "https://sample-project-c990cb-c990cb.kb.us-east-1.aws.elastic.cloud"
    },
    "credentials": {
        "username": "admin",
        "password": "abcd12345"
    }
    (...)
}
----

You can store the project ID as an environment variable for the next requests:

[source,bash]
----
export PROJECT_ID=cace8e65457043698ed3d99da2f053f6
----

[discrete]
[[general-manage-project-with-api-get-project]]
=== Get project

You can retrieve your project details through an API call:

[source,bash]
----
curl -H "Authorization: ApiKey $API_KEY" \
    "https://api.elastic-cloud.com/api/v1/serverless/projects/elasticsearch/${PROJECT_ID}"
----

[discrete]
[[general-manage-project-with-api-get-project-status]]
=== Get project status

The 'status' endpoint indicates whether the project is initialized and ready to be used. In the response, the project's `phase` will change from "initializing" to "initialized" when it is ready:

[source,bash]
----
curl -H "Authorization: ApiKey $API_KEY" \
    "https://api.elastic-cloud.com/api/v1/serverless/projects/elasticsearch/${PROJECT_ID}/status"
----

Example response:

[source,json]
----
{
    "phase":"initializing"
}
----

[discrete]
[[general-manage-project-with-api-reset-credentials]]
=== Reset Credentials

If you lose the credentials provided at the time of the project creation, you can reset the credentials by using the following endpoint:

[source,bash]
----
curl -H "Authorization: ApiKey $API_KEY" \
    -XPOST \
    "https://api.elastic-cloud.com/api/v1/serverless/projects/elasticsearch/${PROJECT_ID}/_reset-credentials"
----

[discrete]
[[general-manage-project-with-api-delete-project]]
=== Delete Project

You can delete your project via the API:

[source,bash]
----
curl -XDELETE -H "Authorization: ApiKey $API_KEY" \
    "https://api.elastic-cloud.com/api/v1/serverless/projects/elasticsearch/${PROJECT_ID}"
----

[discrete]
[[general-manage-project-with-api-update-project]]
=== Update Project

You can update your project using a PATCH request. Only the fields included in the body of the request will be updated.

[source,bash]
----
curl -H "Authorization: ApiKey $API_KEY" \
    -H "Content-Type: application/json" \
    "https://api.elastic-cloud.com/api/v1/serverless/projects/elasticsearch/${PROJECT_ID}" \
    -XPATCH --data '{
        "name": "new name",
        "alias": "new-project-alias"
     }'
----

[discrete]
[[general-manage-project-with-api-list-available-regions]]
=== List available regions

You can obtain the list of regions where projects can be created using the API:

[source,bash]
----
curl -H "Authorization: ApiKey $API_KEY" \
    "https://api.elastic-cloud.com/api/v1/serverless/regions"
----
