[[elasticsearch-billing]]
= {es} billing dimensions

// :description: Learn about how Elasticsearch usage affects pricing.
// :keywords: serverless, elasticsearch, overview

preview:[]

{es} is priced based on the consumption of the underlying
infrastructure used to support your use case, with the performance
characteristics you need. We measure by Virtual Compute Units (VCUs), which is a
slice of RAM, CPU and local disk for caching. The number of VCUs required will
depend on the amount and the rate of data sent to {es} and retained,
and the number of searches and latency you require for searches. In addition, if
you required {ml} for inference or NLP tasks, those VCUs are also
metered and billed.

include::../partials/minimum-vcus-detail.asciidoc[]

[discrete]
[[elasticsearch-billing-information-about-the-vcu-types-search-ingest-and-ml]]
== Information about the VCU types (Search, Ingest, and ML)

There are three VCU types in {es}:

* **Indexing** — The VCUs used to index the incoming documents to be
stored in {es}.
* **Search** — The VCUs used to return search results with the latency and
Queries per Second (QPS) you require.
* **Machine Learning** — The VCUs used to perform inference, NLP tasks, and other ML activities.

[discrete]
[[elasticsearch-billing-information-about-the-search-ai-lake-dimension-gb]]
== Information about the Search AI Lake dimension (GB)

For {es}, the Search AI Lake is where data is stored and retained. This is
charged in GBs for the size of data at rest. Depending on the enrichment,
vectorization and other activities during ingest, this size may be different
from the original size of the source data.

[discrete]
[[elasticsearch-billing-managing-elasticsearch-costs]]
== Managing {es} costs

You can control costs in a number of ways. Firstly there is the amount of
data that is retained. {es} will ensure that the most recent data is
cached, allowing for fast retrieval. Reducing the amount of data means fewer
Search VCUs may be required. If you need lower latency, then more Search VCUs
can be added by adjusting the Search Power. A further refinement is for data streams that can be used to store
time series data. For that type of data, you can further define the number of
days of data you want cacheable, which will affect the number of Search VCUs and
therefore the cost. Note that {es-serverless} maintains and bills for
https://www.elastic.co/pricing/serverless-search#what-are-the-minimum-compute-resource-vcus-on-elasticsearch-serverless[minimum compute resource Ingest and Search VCUs].

For detailed {es-serverless} project rates, check the
https://www.elastic.co/pricing/serverless-search[{es-serverless} pricing page].
