[[elasticsearch-billing]]
= {es} billing dimensions

// :description: Learn about how Elasticsearch usage affects pricing.
// :keywords: serverless, elasticsearch, overview

Elasticsearch is priced based on consumption of the underlying
infrastructure that supports your use case, with the performance
characteristics you need. Measurements are in Virtual Compute Units (VCUs).
Each VCU represents a fraction of RAM, CPU, and local disk for caching.

The number of VCUs you need is determined by:

* Volume and ingestion rate of your data
* Data retention requirements 
* Search query volume
* Search Power setting
* Machine learning usage

[discrete]
[[elasticsearch-billing-information-about-the-vcu-types-search-ingest-and-ml]]
== VCU types: Search, Indexing, and ML

Elasticsearch uses three VCU types:

* **Indexing:** The VCUs used to index incoming documents.
* **Search:** The VCUs used to return search results, with the latency and
queries per second (QPS) you require.
* **Machine learning:** The VCUs used to perform inference, NLP tasks, and other ML activities.

[discrete]
[[elasticsearch-billing-information-about-the-search-ai-lake-dimension-gb]]
== Data storage and billing


{es-serverless} projects store data in the <<elasticsearch-manage-project-search-ai-lake-settings,Search AI Lake>>. You are charged per GB of stored data at rest. Note that if you perform operations at ingest such as vectorization or enrichment, the size of your stored data will differ from the size of the original source data.

[discrete]
[[elasticsearch-billing-managing-elasticsearch-costs]]
== Managing {es} costs

You can control costs by using a lower Search Power setting or reducing the amount 
of retained data. 

* **Search Power setting:** <<elasticsearch-manage-project-search-power-settings,Search Power>> controls the speed of searches against your data. With Search Power, you can 
improve search performance by adding more resources for querying, or you can reduce provisioned 
resources to cut costs.
* **Time series data retention:** By limiting the number of days of <<elasticsearch-ingest-time-series-data,time series data>> that are available for caching, 
you can reduce the number of search VCUs required. 

For detailed {es-serverless} project rates, see the https://www.elastic.co/pricing/serverless-search[{es-serverless} pricing page].
