[[elasticsearch-search-your-data]]
= Search your data

// :description: Learn options for searching your data in Elasticsearch Serverless.
// :keywords: serverless, elasticsearch, search

Searching your data in {es-serverless} works the same way as in other Elasticsearch deployments.
If you haven't used {es} before, you can learn the basics in the {ref}/elasticsearch-intro.html[core {es} documentation].

You can use the https://www.elastic.co/docs/api/doc/elasticsearch-serverless[{es-serverless} REST APIs] to search your data using any HTTP client, including the <<elasticsearch-clients,{es} client libraries>>, or directly in <<devtools-run-api-requests-in-the-console, Console>>.

You can also run searches using {kibana-ref}/discover.html[Discover] in your project's UI.

[TIP]
====
Try our hands-on {ref}/quickstart.html#quickstart-list[quick start tutorials] in the core {es} documentation to get started, or check out our https://github.com/elastic/elasticsearch-labs/tree/main/notebooks#readme[Python notebooks].
====

[discrete]
[[elasticsearch-search-your-data-query-languages-overview]]
== Query languages

Learn about the various query languages you can use to search your data in the {ref}/search-analyze.html[core {es} documentation].

[discrete]
[[elasticsearch-search-your-data-learn-more]]
== Learn more

The subpages in this section provide some high-level information about selected important search-related topics:

* <<elasticsearch-search-your-data-the-search-api, The search API>>
* <<elasticsearch-knn-search,K-Nearest Neighbors (KNN) search>>
* <<elasticsearch-reference-semantic-search, Semantic search>>