[[elasticsearch-search-your-data-the-search-api]]
= The search API

// :description: Run queries and aggregations with the search API.
// :keywords: serverless, elasticsearch, API

A _search_ consists of one or more queries that are combined and sent to {es}.
Documents that match a search's queries are returned in the _hits_, or
_search results_, of the response.

A search may also contain additional information used to better process its
queries. For example, a search may be limited to a specific index or only return
a specific number of results.

You can use the https://www.elastic.co/docs/api/doc/elasticsearch-serverless/group/endpoint-search[search API] to search and
aggregate data stored in {es} data streams or indices.

For more information, refer to {ref}/search-your-data.html[the search API overview] in the core {es} docs.

[discrete]
[[elasticsearch-search-your-data-the-query-dsl]]
== Query DSL

{ref}/query-dsl.html[Query DSL] is full-featured JSON-style query language that enables complex searching, filtering, and aggregations.

The `_search` API's `query` request body parameter accepts queries written in
Query DSL.

[discrete]
[[elasticsearch-search-your-data-the-retrievers]]
== Retrievers

Retrievers are an alternative to Query DSL that allow you to configure complex retrieval pipelines using a simplified syntax.
Retrievers simplify the user experience by allowing entire retrieval pipelines to be configured in a single `_search` API call.

Learn more in the {ref}/retrievers-overview.html[Retrievers overview] in the core {es} docs.

