Review the latest improvements and changes to Elastic Cloud Serverless.

For serverless API changes, refer to https://www.elastic.co/docs/api/changes[APIs Changelog].

For serverless changes in Cloud Console, refer to https://www.elastic.co/guide/en/cloud/current/ec-release-notes.html[Elasticsearch Service Documentation: Release notes].

[discrete]
[[serverless-changelog-01062025]]
=== January 6, 2025

[discrete]
[[deprecations-01062025]]
==== Deprecations
* Disables Elastic Observability Serverless log stream and settings pages ({kibana-pull}203996[#203996]). 
* Removes Logs Explorer in Elastic Observability Serverless ({kibana-pull}203685[#203685]). 

[discrete]
[[features-enhancements-01062025]]
=== Features and enhancements
* Introduces case observables in Elastic Security Serverless ({kibana-pull}190237[#190237]).
* Adds a JSON field called "additional fields" to ServiceNow cases when sent using connector, containing the internal names of the ServiceNow table columns ({kibana-pull}201948[#201948]).
* Adds the ability to configure the appearance color mode to sync dark mode with the system value ({kibana-pull}203406[#203406]).
* Makes the "Copy" action visible on cell hover in Discover ({kibana-pull}204744[#204744]).
* Updates the `EnablementModalCallout` name to `AdditionalChargesMessage` in Elastic Security Serverless ({kibana-pull}203061[#203061]).
* Adds more control over which Elastic Security Serverless alerts in Attack Discovery are included as context to the large language model ({kibana-pull}205070[#205070]).
* Adds a consistent layout and other UI enhancements for {ml} pages ({kibana-pull}203813[#203813]).

[discrete]
[[fixes-01062025]]
==== Fixes
* Fixes an issue that caused dashboards to lag when dragging the time slider ({kibana-pull}201885[#201885]).
* Updates the CloudFormation template to the latest version and adjusts the documentation to reflect the use of a single Firehose stream created by the new template ({kibana-pull}204185[#204185]).
* Fixes Integration and Datastream name validation in Elastic Security Serverless ({kibana-pull}204943[#204943]).
* Fixes an issue in the Automatic Import process where there is now inclusion of the `@timestamp` field in ECS field mappings whenever possible ({kibana-pull}204931[#204931]).
* Allows Automatic Import to safely parse Painless field names that are not valid Painless identifiers in `if` contexts ({kibana-pull}205220[#205220]).
* Aligns the Box Native Connector configuration fields with the source of truth in the connectors codebase, correcting mismatches and removing unused configurations ({kibana-pull}203241[#203241]).
* Fixes the "Show all agent tags" option in Fleet when the agent list is filtered ({kibana-pull}205163[#205163]).
* Updates the Results Explorer flyout footer buttons alignment in Data Frame Analytics ({kibana-pull}204735[#204735]).
* Adds a missing space between lines in the Data Frame Analytics delete job modal ({kibana-pull}204732[#204732]).
* Fixes an issue where the Refresh button in the Anomaly Detection Datafeed counts table was unresponsive ({kibana-pull}204625[#204625]).
* Fixes the inference timeout check in File Upload ({kibana-pull}204722[#204722]).
* Fixes the side bar navigation for the Data Visualizer ({kibana-pull}205170[#205170]).

[discrete]
[[serverless-changelog-12162024]]
== December 16, 2024

[discrete]
[[deprecations-12162024]]
=== Deprecations
* Deprecates the `discover:searchFieldsFromSource` setting ({kibana-pull}202679[#202679]).
* Disables scripted field creation in the Data Views management page ({kibana-pull}202250[#202250]).
* Removes all logic based on the following settings: `xpack.reporting.roles.enabled`,
`xpack.reporting.roles.allow` ({kibana-pull}200834[#200834]).
* Removes the legacy table from Discover ({kibana-pull}201254[#201254]).
* Deprecates ephemeral tasks from action and alerting plugins ({kibana-pull}197421[#197421]).

[discrete]
[[features-enhancements-12162024]]
=== Features and enhancements
* Optimizes the Kibana Trained Models API ({kibana-pull}200977[#200977]).
* Adds a *Create Case* action to the *Log rate analysis* page ({kibana-pull}201549[#201549]).
* Improves AI Assistant's response quality by giving it access to Elastic's product documentation ({kibana-pull}199694[#199694]).
* Adds support for suppressing EQL sequence alerts ({kibana-pull}189725[#189725]).
* Adds an *Advanced settings* section to the SLO form ({kibana-pull}200822[#200822]). 
* Adds a new sub-feature privilege under **Synthetics and Uptime** `Can manage private locations` ({kibana-pull}201100[#201100]).


[discrete]
[[fixes-12162024]]
=== Fixes
* Fixes point visibility regression ({kibana-pull}202358[#202358]).
* Improves help text of creator and view count features on dashboard listing page ({kibana-pull}202488[#202488]).
* Highlights matching field values when performing a KQL search on a keyword field ({kibana-pull}201952[#201952]).
* Supports "Inspect" in saved search embeddables ({kibana-pull}202947[#202947]).
* Fixes your ability to clear the user-specific system prompt ({kibana-pull}202279[#202279]).
* Fixes error when opening rule flyout ({kibana-pull}202386[#202386]).
* Fixes to Ops Genie as a default connector ({kibana-pull}201923[#201923]).
* Fixes actions on charts ({kibana-pull}202443[#202443]).
* Adds flyout to table view in Infrastructure Inventory ({kibana-pull}202646[#202646]).
* Fixes service names with spaces not being URL encoded properly for `context.viewInAppUrl` ({kibana-pull}202890[#202890]).
* Allows access query logic to handle user ID and name conditions ({kibana-pull}202833[#202833]).
* Fixes APM rule error message for invalid KQL filter ({kibana-pull}203096[#203096]).
* Rejects CEF logs from Automatic Import and redirects you to the CEF integration instead ({kibana-pull}201792[#201792]).
* Updates the install rules title and message ({kibana-pull}202226[#202226]).
* Fixes error on second entity engine init API call ({kibana-pull}202903[#202903]).
* Restricts unsupported log formats ({kibana-pull}202994[#202994]).
* Removes errors related to Enterprise Search nodes ({kibana-pull}202437[#202437]).
* Improves web crawler name consistency ({kibana-pull}202738[#202738]).
* Fixes editor cursor jumpiness ({kibana-pull}202389[#202389]).
* Fixes rollover datastreams on subobjects mapper exception ({kibana-pull}202689[#202689]).
* Fixes spaces sync to retrieve 10,000 trained models ({kibana-pull}202712[#202712]).
* Fixes log rate analysis embeddable error on the Alerts page ({kibana-pull}203093[#203093]).
* Fixes Slack API connectors not displayed under Slack connector type when adding new connector to rule ({kibana-pull}202315[#202315]).


[discrete]
[[serverless-changelog-12092024]]
== December 9, 2024

[discrete]
[[features-enhancements-12092024]]
=== Features and enhancements
* Elastic Observability Serverless adds a new sub-feature for managing private locations ({kibana-pull}201100[#201100]).
* Elastic Observability Serverless adds the ability to configure SLO advanced settings from the UI ({kibana-pull}200822[#200822]).
* Elastic Security Serverless adds support for suppressing EQL sequence alerts ({kibana-pull}189725[#189725]).
* Elastic Security Serverless adds a `/trained_models_list` endpoint to retrieve complete data for the Trained Model UI ({kibana-pull}200977[#200977]).
* Machine Learning adds an action to include log rate analysis in a case ({kibana-pull}199694[#199694]).
* Machine Learning enhances the Kibana API to optimize trained models ({kibana-pull}201549[#201549]).

[discrete]
[[fixes-12092020]]
=== Fixes
* Fixes Slack API connectors not being displayed under the Slack connector type when adding a new connector to a rule in Alerting ({kibana-pull}202315[#202315]).
* Fixes point visibility regression in dashboard visualizations ({kibana-pull}202358[#202358]).
* Improves help text for creator and view count features on the Dashboard listing page ({kibana-pull}202488[#202488]).
* Highlights matching field values when performing a KQL search on a keyword field in Discover ({kibana-pull}201952[#201952]).
* Adds support for the *Inspect* option in saved search embeddables in Discover ({kibana-pull}202947[#202947]).
* Enables the ability to clear user-specific system prompts in Elastic Observability Serverless ({kibana-pull}202279[#202279]).
* Fixes an error when opening the rule flyout in Elastic Observability Serverless ({kibana-pull}202386[#202386]).
* Improves handling of Opsgenie as the default connector in Elastic Observability Serverless ({kibana-pull}201923[#201923]).
* Fixes issues with actions on charts in Elastic Observability Serverless ({kibana-pull}202443[#202443]).
* Adds a flyout to the table view in Infrastructure Inventory in Elastic Observability Serverless ({kibana-pull}202646[#202646]).
* Fixes service names with spaces not being URL-encoded properly for {{context.viewInAppUrl}} in Elastic Observability Serverless ({kibana-pull}202890[#202890]).
* Enhances access query logic to handle user ID and name conditions in Elastic Observability Serverless ({kibana-pull}202833[#202833]).
* Fixes an APM rule error message when a KQL filter is invalid in Elastic Observability Serverless ({kibana-pull}203096[#203096]).
* Restricts and rejects CEF logs in automatic import and redirects them to the CEF integration in Elastic Security Serverless ({kibana-pull}201792[#201792]).
* Updates the copy of the install rules title and message in Elastic Security Serverless ({kibana-pull}202226[#202226]).
* Clears errors on the second entity engine initialization API call in Elastic Security Serverless ({kibana-pull}202903[#202903]).
* Restricts unsupported log formats in Elastic Security Serverless ({kibana-pull}202994[#202994]).
* Removes errors related to Enterprise Search nodes in Elasticsearch Serverless ({kibana-pull}202437[#202437]).
* Ensures consistency in web crawler naming in Elasticsearch Serverless ({kibana-pull}202738[#202738]).
* Fixes editor cursor jumpiness in ES|QL ({kibana-pull}202389[#202389]).
* Implements rollover of data streams on subobject mapper exceptions in Fleet ({kibana-pull}202689[#202689]).
* Fixes trained models to retrieve up to 10,000 models when spaces are synced in Machine Learning ({kibana-pull}202712[#202712]).
* Fixes a Log Rate Analysis embeddable error on the Alerts page in AiOps ({kibana-pull}203093[#203093]).

[discrete]
[[serverless-changelog-12032024]]
== December 3, 2024

[discrete]
[[features-enhancements-12032024]]
=== Features and enhancements
* Adds tabs for Import Entities and Engine Status to the Entity Store ({kibana-pull}201235[#201235]).
* Adds status tracking for agentless integrations to {fleet} ({kibana-pull}199567[#199567]).
* Adds a new {ml} module that can detect anomalous activity in host-based logs ({kibana-pull}195582[#195582]).
* Allows custom Mapbox Vector Tile sources to style map layers and provide custom legends ({kibana-pull}200656[#200656]).
* Excludes stale SLOs from counts of healthy and violated SLOs ({kibana-pull}201027[#201027]).
* Adds a **Continue without adding integrations** button to the {elastic-sec} Dashboards page that takes you to the Entity Analytics dashboard ({kibana-pull}201363[#201363]).
* Displays visualization descriptions under their titles ({kibana-pull}198816[#198816]).

[discrete]
[[fixes-12032024]]
=== Fixes
* Hides the *Clear* button when no filters are selected ({kibana-pull}200177[#200177]).
* Fixes a mismatch between how wildcards were handled in previews versus actual rule executions ({kibana-pull}201553[#201553]).
* Fixes incorrect Y-axis and hover values in the Service Inventory's Log rate chart ({kibana-pull}201361[#201361]).
* Disables the *Add note* button in the alert details flyout for users who lack privileges ({kibana-pull}201707[#201707]).
* Fixes the descriptions of threshold rules that use cardinality ({kibana-pull}201162[#201162]).
* Disables the *Install All* button on the **Add Elastic Rules** page when rules are installing ({kibana-pull}201731[#201731]).
* Reintroduces a data usage warning on the Entity Analytics Enablement modal ({kibana-pull}201920[#201920]).
* Improves accessibility for the **Create a connector** page ({kibana-pull}201590[#201590]).
* Fixes a bug that could cause {agents} to get stuck updating during scheduled upgrades ({kibana-pull}202126[#202126]).
* Fixes a bug related to starting {ml} deployments with autoscaling and no active nodes ({kibana-pull}201256[#201256]).
* Initializes saved objects when the **Trained Model** page loads ({kibana-pull}201426[#201426]).
* Fixes the display of deployment stats for unallocated deployments of {ml} models ({kibana-pull}202005[#202005]).
* Enables the solution type search for instant deployments ({kibana-pull}201688[#201688]).
* Improves the consistency of alert counts across different views ({kibana-pull}202188[#202188]).
