[[serverless-known-issues]]
= Serverless known issues
++++
<titleabbrev>Known issues</titleabbrev>
++++

[discrete]
[[known-issues-201820]]
== Exceptions tab fails to load

On December 5, 2024, it was discovered the {sec-serverless} **Exceptions** tab fails to load when exceptions contain comments with newline characters (`\n`). For details, refer to ({kibana-issue}201820[#201820]).

*Custom rules workaround* + 

. Go to the **Rules** page, then <<import-export-rules-ui,export>> the rule or rules with the exception lists with newline characters. 
. Open the `.ndjson` file, then remove the newline characters from the `comments`.
. Go to the **Rules** page, then <<import-export-rules-ui,re-import>> the rules. Make sure to select **Overwrite existing exception lists with conflicting "list_id"**.

*Prebuilt rules workaround* + 

. For the exception lists with newline characters, fetch the IDs associated with the rule.
.. Go to the **Rules** page.
.. Open the rule details, then go to the page URL.
.. Copy the URL id string. 
+
For example, in the http://host.name/app/security/rules/id/167a5f6f-2148-4792-8226-b5e7a58ef46e URL, copy the `167a5f6f-2148-4792-8226-b5e7a58ef46e` id string.
.. To specify the `id` when fetching the rule details, use the {api-kibana-serverless}/operation/operation-readrule[retrieve a detection rule API]:
+
[source,console]
----
curl -H 'Authorization: ApiKey API_KEY_HERE' -H 'kbn-xsrf: true' -H 'elastic-api-version: 2023-10-31' KIBANA_URL/api/detection_engine/rules?id=167a5f6f-2148-4792-8226-b5e7a58ef46e
----
+
The JSON response contains the `id`, `list_id`, and `namespace_type` values in the `exceptions_list` key: 
+
[source,console]
----
{
  "id": "167a5f6f-2148-4792-8226-b5e7a58ef46e",
  "exceptions_list": [
    {
      "id": "490525a2-eb66-4320-95b5-88bdd1302dc4",
      "list_id": "f75aae6f-0229-413f-881d-81cb3abfbe2d",
      "namespace_type": "single"
    }
  ]
}
----
+
. To retrieve the exception list with newline characters, use the export exceptions API with the `id`, `list_id`, and `namespace_type` values:
+
[source,console]
----
curl -XPOST -H 'Authorization: ApiKey API_KEY_HERE' -H 'kbn-xsrf: true' -H 'elastic-api-version: 2023-10-31' 'KIBANA_URL/api/exception_lists/_export?list_id=f75aae6f-0229-413f-881d-81cb3abfbe2d&id=490525a2-eb66-4320-95b5-88bdd1302dc4&namespace_type=single' -o list.ndjson
----
+
. Open the `.ndjson` file, then remove the newline characters from the `comments[].comment` values.
. Go to the <<security-shared-exception-lists,**Shared Exception Lists**>> page.
. To re-import the exception list, use the **Import exception lists** option.
+
Since the exception list exists, the import fails, and the option to overwrite the existing list appears. 
. Select the overwrite option, then resubmit the request to import the exception list.

NOTE: To export and re-import exceptions for the Elastic Endpoint rule, use the <<security-shared-exception-lists,**Shared Exception Lists**>> page.