[[general-user-profile]]
= Update your user profile

// :description: Manage your profile settings.
// :keywords: serverless, general, profile, update

To edit your user profile, go to the user icon on the header bar and select **Profile**.

[discrete]
[[general-user-profile-update-your-email-address]]
== Update your email address

Your email address is used to sign in. If needed, you can change this email address.

. In the **Profile** section, by **Email address**, select **Edit**.
. Enter a new email address and your current password.
+
An email is sent to the new address with a link to confirm the change. If you don't get the email after a few minutes, check your spam folder.

[discrete]
[[general-user-profile-change-your-password]]
== Change your password

When you signed up with your email address, you selected a password that you use to log in to the Elastic Cloud console. If needed, you can change this password.

If you know your current password:

. Navigate to the **Password** section and select **Change password**.
. Enter the current password and provide the new password that you want to use.

If you don't know your current password:

. At the login screen for the Elastic Cloud console, select the link **Forgot password?**
. Enter the email address for your account and select **Reset password**.
+
An email is sent to the address you specified with a link to reset the password. If you don't get the email after a few minutes, check your spam folder.

[discrete]
[[general-user-profile-enable-multi-factor-authentication]]
== Enable multi-factor authentication

To add an extra layer of security, you can either set up Google authenticator or text messaging on a mobile device.

[TIP]
====
Before you start using multi-factor authentication, verify that your device has SMS capabilities or download the Google Authenticator application onto your device.
====

To enable multi-factor authentication, you must enroll your device.

. Navigate to the **Multi-factor authentication** section.
. Select **Configure** to enable the Authenticator app or **Add a phone number** to enable the Text message.

If the device you want to remove is your only enrolled device, you must disable multi-factor authentication first. If your device is lost or stolen, contact https://support.elastic.co/[support].
